version: '1.1'
services:
  db:
    container_name: eventbookingdb
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    volumes:
      - eventsdb:/var/opt/mssql/data
    restart: always
    environment:
      MSSQL_USER: SA
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: Ebookingsapp@123
      MSSQL_PID: Developer
volumes:
  eventsdb:
    driver: local

